export const codes = {
  FORBIDDEN: 'FORBIDDEN',
  MISSING_USER: 'MISSING_USER',
  MISSING_TRACK: 'MISSING_TRACK',
  MISSING_TRIP: 'MISSING_TRIP',
  USER_CONFLICT: 'USER_CONFLICT',
  WRONG_LOGIN: 'WRONG_LOGIN',
  WRONG_GPX: 'WRONG_GPX',
  INVALID_TRACKS_ORDER: 'INVALID_TRACKS_ORDER',
} as const
